import asyncio
import os
import sys

# Add parent directory to path to allow importing db
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from db import db

EXERCISES_DATA = [
    # CHEST
    {
        "name": "Barbell Bench Press",
        "category": "Chest",
        "muscleGroup": "Pectorals",
        "equipment": "Barbell",
        "difficulty": "Intermediate",
        "description": "A classic compound chest exercise that builds mass and strength in the upper body.",
        "instructions": "Lie flat on the bench, grip the barbell slightly wider than shoulder-width. Lower the bar to mid-chest and press upward until arms are extended.",
    },
    {
        "name": "Incline Barbell Bench Press",
        "category": "Chest",
        "muscleGroup": "Upper Pectorals",
        "equipment": "Barbell",
        "difficulty": "Intermediate",
        "description": "Targets the clavicular head of the pectoralis major for upper chest development.",
        "instructions": "Set bench to a 30-45 degree incline. Unrack barbell, lower to upper chest, and press straight up.",
    },
    {
        "name": "Decline Barbell Bench Press",
        "category": "Chest",
        "muscleGroup": "Lower Pectorals",
        "equipment": "Barbell",
        "difficulty": "Intermediate",
        "description": "Emphasizes the lower portion of the chest muscles.",
        "instructions": "Secure legs in a decline bench, unrack the bar, lower to lower chest, and press upward.",
    },
    {
        "name": "Flat Dumbbell Press",
        "category": "Chest",
        "muscleGroup": "Pectorals",
        "equipment": "Dumbbell",
        "difficulty": "Beginner",
        "description": "Allows a greater range of motion and independent arm stabilization than a barbell press.",
        "instructions": "Lie on bench with a dumbbell in each hand. Lower dumbbells to chest level and press vertically.",
    },
    {
        "name": "Incline Dumbbell Press",
        "category": "Chest",
        "muscleGroup": "Upper Pectorals",
        "equipment": "Dumbbell",
        "difficulty": "Intermediate",
        "description": "Builds upper chest mass with freedom of wrist positioning and full stretch.",
        "instructions": "Set bench to 30-45 degrees, press dumbbells overhead from shoulder level.",
    },
    {
        "name": "Decline Dumbbell Press",
        "category": "Chest",
        "muscleGroup": "Lower Pectorals",
        "equipment": "Dumbbell",
        "difficulty": "Intermediate",
        "description": "Focuses on lower chest isolation with dumbbells.",
        "instructions": "Lie on decline bench, lower dumbbells to lower chest, and press up.",
    },
    {
        "name": "Dumbbell Chest Flye",
        "category": "Chest",
        "muscleGroup": "Pectorals",
        "equipment": "Dumbbell",
        "difficulty": "Intermediate",
        "description": "Isolation movement focusing on chest stretch and adduction.",
        "instructions": "Lie flat with dumbbells extended. With slight elbow bend, lower weights in an arc until chest stretches, then squeeze back together.",
    },
    {
        "name": "Incline Dumbbell Flye",
        "category": "Chest",
        "muscleGroup": "Upper Pectorals",
        "equipment": "Dumbbell",
        "difficulty": "Intermediate",
        "description": "Upper chest isolation stretch movement.",
        "instructions": "Perform flye motion on an incline bench, focusing on squeezing upper chest at top.",
    },
    {
        "name": "Cable Crossover",
        "category": "Chest",
        "muscleGroup": "Pectorals",
        "equipment": "Cable",
        "difficulty": "Beginner",
        "description": "Provides constant tension across the entire range of chest adduction.",
        "instructions": "Set high pulleys. Stand in center, pull handles down and together across body with slight elbow bend.",
    },
    {
        "name": "Low Cable Flye",
        "category": "Chest",
        "muscleGroup": "Upper Pectorals",
        "equipment": "Cable",
        "difficulty": "Intermediate",
        "description": "Low-to-high cable trajectory targeting upper chest.",
        "instructions": "Attach D-handles to bottom pulleys. Scoop hands upward and forward to chest height.",
    },
    {
        "name": "Chest Dip",
        "category": "Chest",
        "muscleGroup": "Lower Pectorals",
        "equipment": "Bodyweight",
        "difficulty": "Intermediate",
        "description": "Bodyweight compound movement emphasizing lower chest and triceps.",
        "instructions": "Grip parallel bars, lean torso forward ~30 degrees, lower body until elbows hit 90 degrees, press up.",
    },
    {
        "name": "Push-up",
        "category": "Chest",
        "muscleGroup": "Pectorals",
        "equipment": "Bodyweight",
        "difficulty": "Beginner",
        "description": "Fundamental bodyweight upper body exercise.",
        "instructions": "Plank position, hands shoulder-width. Lower chest to floor while keeping core tight, press back up.",
    },
    {
        "name": "Incline Push-up",
        "category": "Chest",
        "muscleGroup": "Lower Pectorals",
        "equipment": "Bodyweight",
        "difficulty": "Beginner",
        "description": "Easier push-up variation with hands elevated.",
        "instructions": "Place hands on bench or elevated surface, lower chest to edge, and press up.",
    },
    {
        "name": "Decline Push-up",
        "category": "Chest",
        "muscleGroup": "Upper Pectorals",
        "equipment": "Intermediate",
        "equipment": "Bodyweight",
        "difficulty": "Intermediate",
        "description": "Harder push-up variation with feet elevated.",
        "instructions": "Elevate feet on bench, place hands on floor, perform push-up targeting upper chest.",
    },
    {
        "name": "Pec Deck Machine Flye",
        "category": "Chest",
        "muscleGroup": "Pectorals",
        "equipment": "Machine",
        "difficulty": "Beginner",
        "description": "Machine isolation providing safe guided chest flye movement.",
        "instructions": "Sit back against pad, grab handles with elbows bent, bring handles together in front of chest.",
    },
    {
        "name": "Chest Press Machine",
        "category": "Chest",
        "muscleGroup": "Pectorals",
        "equipment": "Machine",
        "difficulty": "Beginner",
        "description": "Guided compound pressing machine ideal for beginners or finishing sets.",
        "instructions": "Adjust seat so handles align with mid-chest. Press handles forward until arms are extended.",
    },
    {
        "name": "Resistance Band Chest Press",
        "category": "Chest",
        "muscleGroup": "Pectorals",
        "equipment": "Resistance Band",
        "difficulty": "Beginner",
        "description": "Portable pressing option using elastic resistance.",
        "instructions": "Anchor band behind back, hold ends in hands, press forward extending arms.",
    },

    # BACK
    {
        "name": "Conventional Barbell Deadlift",
        "category": "Back",
        "muscleGroup": "Erector Spinae & Hamstrings",
        "equipment": "Barbell",
        "difficulty": "Advanced",
        "description": "The ultimate posterior chain and full-body strength building lift.",
        "instructions": "Stand with feet hip-width under bar. Hinge hips, grip bar, set back flat, and drive through heels to stand upright.",
    },
    {
        "name": "Sumo Barbell Deadlift",
        "category": "Back",
        "muscleGroup": "Glutes, Quads & Lower Back",
        "equipment": "Barbell",
        "difficulty": "Advanced",
        "description": "Wide stance deadlift variation reducing lower back leverage while increasing leg involvement.",
        "instructions": "Take wide stance with toes pointed out. Grip bar inside knees, drop hips, drive floor away to lockout.",
    },
    {
        "name": "Barbell Bent-Over Row",
        "category": "Back",
        "muscleGroup": "Latissimus Dorsi & Rhomboids",
        "equipment": "Barbell",
        "difficulty": "Intermediate",
        "description": "Primary compound pulling exercise for back thickness.",
        "instructions": "Hinge forward at 45 degrees, grip bar overhand, pull bar to upper abdomen while keeping spine neutral.",
    },
    {
        "name": "Pendlay Row",
        "category": "Back",
        "muscleGroup": "Upper Back & Lats",
        "equipment": "Barbell",
        "difficulty": "Intermediate",
        "description": "Strict bent-over row starting each repetition from the floor.",
        "instructions": "Torso parallel to floor. Explosively pull bar from floor to lower chest, return bar completely to ground.",
    },
    {
        "name": "Single-Arm Dumbbell Row",
        "category": "Back",
        "muscleGroup": "Latissimus Dorsi",
        "equipment": "Dumbbell",
        "difficulty": "Beginner",
        "description": "Unilateral row allowing deep lats stretch and isolation.",
        "instructions": "Place one knee and hand on bench. Pull dumbbell with opposite arm toward hip, squeezing lat.",
    },
    {
        "name": "Incline Dumbbell Row",
        "category": "Back",
        "muscleGroup": "Upper Back & Rhomboids",
        "equipment": "Dumbbell",
        "difficulty": "Beginner",
        "description": "Chest-supported row removing lower back strain.",
        "instructions": "Lie chest-down on incline bench. Row dumbbells toward hips while squeezing shoulder blades.",
    },
    {
        "name": "Lat Pulldown",
        "category": "Back",
        "muscleGroup": "Latissimus Dorsi",
        "equipment": "Cable",
        "difficulty": "Beginner",
        "description": "Vertical cable pulling exercise building back width.",
        "instructions": "Grip wide bar overhand. Sit with thighs secured, pull bar down to upper chest while driving elbows down.",
    },
    {
        "name": "Close-Grip V-Bar Pulldown",
        "category": "Back",
        "muscleGroup": "Latissimus Dorsi & Biceps",
        "equipment": "Cable",
        "difficulty": "Beginner",
        "description": "Neutral-grip vertical pull emphasizing lower lats.",
        "instructions": "Attach V-bar handle. Pull handle down to chest level, leaning back slightly.",
    },
    {
        "name": "Seated Cable Row",
        "category": "Back",
        "muscleGroup": "Rhomboids & Mid-Traps",
        "equipment": "Cable",
        "difficulty": "Beginner",
        "description": "Horizontal cable pulling exercise for mid-back thickness.",
        "instructions": "Sit at cable station, knees slightly bent. Pull handle to mid-section while driving shoulders back.",
    },
    {
        "name": "Pull-up",
        "category": "Back",
        "muscleGroup": "Latissimus Dorsi",
        "equipment": "Bodyweight",
        "difficulty": "Intermediate",
        "description": "Gold standard bodyweight vertical pull.",
        "instructions": "Grip pull-up bar overhand wider than shoulders. Pull chin above bar, lower with control.",
    },
    {
        "name": "Chin-up",
        "category": "Back",
        "muscleGroup": "Latissimus Dorsi & Biceps",
        "equipment": "Bodyweight",
        "difficulty": "Intermediate",
        "description": "Underhand vertical pull with high bicep involvement.",
        "instructions": "Grip bar underhand shoulder-width. Pull chest up to bar, lower under control.",
    },
    {
        "name": "Inverted Row",
        "category": "Back",
        "muscleGroup": "Upper Back",
        "equipment": "Bodyweight",
        "difficulty": "Beginner",
        "description": "Bodyweight horizontal pull using a low bar or TRX straps.",
        "instructions": "Lie under waist-high bar, hold bar, keep body straight, pull chest up to bar.",
    },
    {
        "name": "Seated Machine Row",
        "category": "Back",
        "muscleGroup": "Latissimus Dorsi & Rhomboids",
        "equipment": "Machine",
        "difficulty": "Beginner",
        "description": "Machine-guided horizontal row with adjustable chest pad.",
        "instructions": "Adjust chest pad, grab handles, pull back until elbows pass torso.",
    },
    {
        "name": "Back Extension",
        "category": "Back",
        "muscleGroup": "Erector Spinae & Glutes",
        "equipment": "Bodyweight",
        "difficulty": "Beginner",
        "description": "Hyperextension exercise strengthening lower back and hamstrings.",
        "instructions": "Lock feet in 45-degree bench. Hinge at waist, lower torso, then raise back to alignment with hips.",
    },
    {
        "name": "Resistance Band Lat Pulldown",
        "category": "Back",
        "muscleGroup": "Latissimus Dorsi",
        "equipment": "Resistance Band",
        "difficulty": "Beginner",
        "description": "Vertical pulldown using high-anchored resistance band.",
        "instructions": "Kneel facing band anchor, pull ends down to shoulders while squeezing back.",
    },

    # LEGS
    {
        "name": "Barbell Back Squat",
        "category": "Legs",
        "muscleGroup": "Quadriceps & Glutes",
        "equipment": "Barbell",
        "difficulty": "Intermediate",
        "description": "The king of lower-body strength exercises.",
        "instructions": "Place bar on upper traps. Step out, feet shoulder-width, squat down until thighs are parallel or lower, press up.",
    },
    {
        "name": "Barbell Front Squat",
        "category": "Legs",
        "muscleGroup": "Quadriceps & Core",
        "equipment": "Barbell",
        "difficulty": "Advanced",
        "description": "Quad-dominant squat variation requiring erect torso and rack position.",
        "instructions": "Rest bar on front deltoids with fingertips under bar. Squat deep keeping elbows high.",
    },
    {
        "name": "Goblet Squat",
        "category": "Legs",
        "muscleGroup": "Quadriceps",
        "equipment": "Dumbbell",
        "difficulty": "Beginner",
        "description": "Accessible squat pattern holding a dumbbell at chest height.",
        "instructions": "Hold dumbbell vertically at chest. Squat down between knees, keeping chest up.",
    },
    {
        "name": "Romanian Deadlift (RDL)",
        "category": "Legs",
        "muscleGroup": "Hamstrings & Glutes",
        "equipment": "Barbell",
        "difficulty": "Intermediate",
        "description": "Hip-hinge movement maximizing hamstring stretch and loading.",
        "instructions": "Stand with bar, hinge hips backward with soft knee bend until deep hamstring stretch is felt, contract glutes to return.",
    },
    {
        "name": "Dumbbell Romanian Deadlift",
        "category": "Legs",
        "muscleGroup": "Hamstrings & Glutes",
        "equipment": "Dumbbell",
        "difficulty": "Beginner",
        "description": "Dumbbell version of the RDL for hamstring isolation.",
        "instructions": "Hold dumbbells at thighs, hinge hips back lowering weights past knees, stand upright.",
    },
    {
        "name": "Bulgarian Split Squat",
        "category": "Legs",
        "muscleGroup": "Quadriceps & Glutes",
        "equipment": "Dumbbell",
        "difficulty": "Intermediate",
        "description": "Single-leg squat with rear foot elevated for intense quad/glute development.",
        "instructions": "Place rear foot on bench. Lower front hip until thigh is parallel, push up through front heel.",
    },
    {
        "name": "Dumbbell Walking Lunge",
        "category": "Legs",
        "muscleGroup": "Quadriceps & Glutes",
        "equipment": "Dumbbell",
        "difficulty": "Intermediate",
        "description": "Dynamic unilateral leg training.",
        "instructions": "Hold dumbbells at sides, step forward into lunge until back knee nearly touches ground, step into next stride.",
    },
    {
        "name": "Leg Press Machine",
        "category": "Legs",
        "muscleGroup": "Quadriceps & Glutes",
        "equipment": "Machine",
        "difficulty": "Beginner",
        "description": "Heavy leg pressing with back support and guided sled.",
        "instructions": "Place feet shoulder-width on platform. Release safety, bend knees to 90 degrees, press platform away.",
    },
    {
        "name": "Leg Extension Machine",
        "category": "Legs",
        "muscleGroup": "Quadriceps",
        "equipment": "Machine",
        "difficulty": "Beginner",
        "description": "Isolated quad extension.",
        "instructions": "Sit with pad against lower shins. Extend legs upward until fully straight, lower slowly.",
    },
    {
        "name": "Seated Leg Curl Machine",
        "category": "Legs",
        "muscleGroup": "Hamstrings",
        "equipment": "Machine",
        "difficulty": "Beginner",
        "description": "Isolation movement for hamstring flexion.",
        "instructions": "Sit with pad on back of ankles, flex knees downward pulling pad under seat.",
    },
    {
        "name": "Lying Leg Curl Machine",
        "category": "Legs",
        "muscleGroup": "Hamstrings",
        "equipment": "Machine",
        "difficulty": "Beginner",
        "description": "Prone hamstring isolation.",
        "instructions": "Lie face down, pad on lower calves, curl legs upward toward glutes.",
    },
    {
        "name": "Standing Calf Raise",
        "category": "Legs",
        "muscleGroup": "Gastrocnemius",
        "equipment": "Machine",
        "difficulty": "Beginner",
        "description": "Calf isolation targeting the upper calf muscle.",
        "instructions": "Place shoulders under pads, balls of feet on block. Lower heels for stretch, press up onto toes.",
    },
    {
        "name": "Seated Calf Raise",
        "category": "Legs",
        "muscleGroup": "Soleus",
        "equipment": "Machine",
        "difficulty": "Beginner",
        "description": "Calf isolation targeting the deep soleus muscle.",
        "instructions": "Sit with knees bent under pad. Lower heels, raise calves high onto toes.",
    },
    {
        "name": "Air Bodyweight Squat",
        "category": "Legs",
        "muscleGroup": "Quadriceps",
        "equipment": "Bodyweight",
        "difficulty": "Beginner",
        "description": "Foundational unweighted squat motion.",
        "instructions": "Feet shoulder-width. Sit back into squat depth, drive up standing tall.",
    },
    {
        "name": "Resistance Band Glute Bridge",
        "category": "Legs",
        "muscleGroup": "Glutes",
        "equipment": "Resistance Band",
        "difficulty": "Beginner",
        "description": "Targeted glute activation with elastic abduction band.",
        "instructions": "Band above knees, lie on back. Drive hips toward ceiling squeezing glutes at top.",
    },

    # SHOULDERS
    {
        "name": "Standing Barbell Overhead Press (OHP)",
        "category": "Shoulders",
        "muscleGroup": "Deltoids & Triceps",
        "equipment": "Barbell",
        "difficulty": "Intermediate",
        "description": "Classic strict overhead pressing movement.",
        "instructions": "Rest bar on front rack. Press bar vertically overhead until lockout, keeping core rigid.",
    },
    {
        "name": "Seated Dumbbell Shoulder Press",
        "category": "Shoulders",
        "muscleGroup": "Anterior & Lateral Deltoids",
        "equipment": "Dumbbell",
        "difficulty": "Beginner",
        "description": "Seated press providing stability and shoulder mass.",
        "instructions": "Sit on upright bench. Press dumbbells from shoulder height to lockout overhead.",
    },
    {
        "name": "Arnold Press",
        "category": "Shoulders",
        "muscleGroup": "Deltoids",
        "equipment": "Dumbbell",
        "difficulty": "Intermediate",
        "description": "Rotational overhead press engaging all three deltoid heads.",
        "instructions": "Start with dumbbells at chest, palms facing you. Rotate hands as you press overhead so palms face forward.",
    },
    {
        "name": "Dumbbell Lateral Raise",
        "category": "Shoulders",
        "muscleGroup": "Lateral Deltoids",
        "equipment": "Dumbbell",
        "difficulty": "Beginner",
        "description": "The premier exercise for shoulder width.",
        "instructions": "Hold dumbbells at sides. Raise arms out to sides until parallel with floor, lower with control.",
    },
    {
        "name": "Cable Lateral Raise",
        "category": "Shoulders",
        "muscleGroup": "Lateral Deltoids",
        "equipment": "Cable",
        "difficulty": "Beginner",
        "description": "Provides smooth continuous tension for side delts.",
        "instructions": "Attach single handle to low pulley. Raise cable out to side to shoulder height.",
    },
    {
        "name": "Dumbbell Front Raise",
        "category": "Shoulders",
        "muscleGroup": "Anterior Deltoids",
        "equipment": "Dumbbell",
        "difficulty": "Beginner",
        "description": "Isolation for the front head of the shoulder.",
        "instructions": "Hold dumbbells in front of thighs. Raise one or both dumbbells straight forward to eye level.",
    },
    {
        "name": "Rear Delt Dumbbell Flye",
        "category": "Shoulders",
        "muscleGroup": "Posterior Deltoids",
        "equipment": "Dumbbell",
        "difficulty": "Beginner",
        "description": "Bent-over movement targeting rear delts for 3D shoulder shape.",
        "instructions": "Hinge forward at waist. Raise dumbbells out to sides squeezing back of shoulders.",
    },
    {
        "name": "Face Pull",
        "category": "Shoulders",
        "muscleGroup": "Rear Delts & External Rotators",
        "equipment": "Cable",
        "difficulty": "Beginner",
        "description": "Crucial shoulder health and posture exercise.",
        "instructions": "Attach rope to high pulley. Pull rope to face, separating ends and externally rotating shoulders.",
    },
    {
        "name": "Barbell Shrug",
        "category": "Shoulders",
        "muscleGroup": "Upper Trapezius",
        "equipment": "Barbell",
        "difficulty": "Beginner",
        "description": "Heavy trap isolation exercise.",
        "instructions": "Hold barbell at thighs overhand. Elevate shoulders straight up toward ears, hold briefly, lower down.",
    },
    {
        "name": "Dumbbell Shrug",
        "category": "Shoulders",
        "muscleGroup": "Upper Trapezius",
        "equipment": "Dumbbell",
        "difficulty": "Beginner",
        "description": "Trap builder allowing natural arm alignment at sides.",
        "instructions": "Hold heavy dumbbells at sides. Elevate shoulders upward toward ears.",
    },
    {
        "name": "Resistance Band Pull-Apart",
        "category": "Shoulders",
        "muscleGroup": "Rear Delts & Rhomboids",
        "equipment": "Resistance Band",
        "difficulty": "Beginner",
        "description": "Postural warm-up and rear delt activator.",
        "instructions": "Hold band out front at shoulder height. Pull arms apart until band touches chest.",
    },

    # BICEPS
    {
        "name": "Barbell Bicep Curl",
        "category": "Biceps",
        "muscleGroup": "Biceps Brachii",
        "equipment": "Barbell",
        "difficulty": "Beginner",
        "description": "Foundation lift for building overall bicep size.",
        "instructions": "Grip bar underhand shoulder-width. Curl bar up toward chest keeping elbows pinned at sides.",
    },
    {
        "name": "EZ-Bar Preacher Curl",
        "category": "Biceps",
        "muscleGroup": "Biceps Brachii",
        "equipment": "Barbell",
        "difficulty": "Intermediate",
        "description": "Strict isolation preventing cheating by supporting triceps on preacher pad.",
        "instructions": "Rest arms over preacher bench pad. Lower bar until arms extend, curl up toward chin.",
    },
    {
        "name": "Standing Dumbbell Curl",
        "category": "Biceps",
        "muscleGroup": "Biceps Brachii",
        "equipment": "Dumbbell",
        "difficulty": "Beginner",
        "description": "Standard bicep curl with supinating wrist motion.",
        "instructions": "Hold dumbbells at sides. As you curl up, rotate palms facing upward at top.",
    },
    {
        "name": "Hammer Curl",
        "category": "Biceps",
        "muscleGroup": "Brachialis & Brachioradialis",
        "equipment": "Dumbbell",
        "difficulty": "Beginner",
        "description": "Neutral-grip curl building arm thickness and forearm strength.",
        "instructions": "Hold dumbbells with palms facing each other (neutral grip). Curl straight up without rotating wrists.",
    },
    {
        "name": "Incline Dumbbell Curl",
        "category": "Biceps",
        "muscleGroup": "Biceps Long Head",
        "equipment": "Dumbbell",
        "difficulty": "Intermediate",
        "description": "Stretches the long head of the bicep for maximal peak development.",
        "instructions": "Lie back on 45-degree bench letting arms hang straight down. Curl dumbbells upward.",
    },
    {
        "name": "Concentration Curl",
        "category": "Biceps",
        "muscleGroup": "Biceps Brachii",
        "equipment": "Dumbbell",
        "difficulty": "Beginner",
        "description": "Seated single-arm curl isolating the bicep peak.",
        "instructions": "Sit on bench, brace elbow against inner thigh. Curl dumbbell toward shoulder.",
    },
    {
        "name": "Cable Bicep Curl",
        "category": "Biceps",
        "muscleGroup": "Biceps Brachii",
        "equipment": "Cable",
        "difficulty": "Beginner",
        "description": "Provides constant tension throughout the curling motion.",
        "instructions": "Attach straight or EZ-bar to low cable. Curl bar up to chin level.",
    },
    {
        "name": "Machine Bicep Curl",
        "category": "Biceps",
        "muscleGroup": "Biceps Brachii",
        "equipment": "Machine",
        "difficulty": "Beginner",
        "description": "Guided machine curl for safe bicep burnout.",
        "instructions": "Adjust seat, rest elbows on pad, grab handles, curl upward.",
    },
    {
        "name": "Resistance Band Bicep Curl",
        "category": "Biceps",
        "muscleGroup": "Biceps Brachii",
        "equipment": "Resistance Band",
        "difficulty": "Beginner",
        "description": "Portable bicep exercise with increasing tension at top.",
        "instructions": "Step on center of band, hold handles, curl hands toward shoulders.",
    },

    # TRICEPS
    {
        "name": "Barbell Skullcrusher (Lying Triceps Extension)",
        "category": "Triceps",
        "muscleGroup": "Triceps (Long & Lateral Heads)",
        "equipment": "Barbell",
        "difficulty": "Intermediate",
        "description": "Classic mass builder for all three heads of the triceps.",
        "instructions": "Lie flat with EZ-bar extended above chest. Bend elbows to lower bar toward forehead, extend back up.",
    },
    {
        "name": "Close-Grip Barbell Bench Press",
        "category": "Triceps",
        "muscleGroup": "Triceps & Chest",
        "equipment": "Barbell",
        "difficulty": "Intermediate",
        "description": "Heavy compound press shifting focus onto triceps.",
        "instructions": "Grip barbell shoulder-width apart. Lower bar to lower sternum keeping elbows close to ribs, press up.",
    },
    {
        "name": "Triceps Dip",
        "category": "Triceps",
        "muscleGroup": "Triceps",
        "equipment": "Bodyweight",
        "difficulty": "Intermediate",
        "description": "Upright bodyweight dip isolating triceps strength.",
        "instructions": "Hold parallel dip bars upright. Lower body vertically keeping torso upright until elbows hit 90 degrees, press up.",
    },
    {
        "name": "Bench Dip",
        "category": "Triceps",
        "muscleGroup": "Triceps",
        "equipment": "Bodyweight",
        "difficulty": "Beginner",
        "description": "Accessible bodyweight dip using flat bench.",
        "instructions": "Hands on edge of bench behind back, legs extended. Bend elbows lowering hips to floor, push back up.",
    },
    {
        "name": "Cable Triceps Pushdown",
        "category": "Triceps",
        "muscleGroup": "Triceps Lateral Head",
        "equipment": "Cable",
        "difficulty": "Beginner",
        "description": "Staple isolation exercise for horseshoe triceps.",
        "instructions": "Attach straight or angled bar to high pulley. Keep elbows tucked at sides, press bar down to thighs.",
    },
    {
        "name": "Cable Rope Extension",
        "category": "Triceps",
        "muscleGroup": "Triceps",
        "equipment": "Cable",
        "difficulty": "Beginner",
        "description": "Rope variation allowing outward flare at bottom lockout.",
        "instructions": "Attach rope handle to high cable. Push down and spread ends apart at bottom of motion.",
    },
    {
        "name": "Overhead Dumbbell Triceps Extension",
        "category": "Triceps",
        "muscleGroup": "Triceps Long Head",
        "equipment": "Dumbbell",
        "difficulty": "Beginner",
        "description": "Overhead extension targeting the long head of the triceps.",
        "instructions": "Hold dumbbell with both hands overhead. Lower weight behind neck by flexing elbows, extend back up.",
    },
    {
        "name": "Dumbbell Triceps Kickback",
        "category": "Triceps",
        "muscleGroup": "Triceps",
        "equipment": "Dumbbell",
        "difficulty": "Beginner",
        "description": "Bent-over dumbbell extension focusing on peak contraction.",
        "instructions": "Hinge forward with upper arm parallel to floor. Extend forearm backward until elbow locks out.",
    },
    {
        "name": "Resistance Band Triceps Pushdown",
        "category": "Triceps",
        "muscleGroup": "Triceps",
        "equipment": "Resistance Band",
        "difficulty": "Beginner",
        "description": "Elastic pushdown for home or travel workouts.",
        "instructions": "Anchor band up high, hold ends, press downward locking out arms.",
    },

    # CORE
    {
        "name": "Plank",
        "category": "Core",
        "muscleGroup": "Transverse Abdominis & Core",
        "equipment": "Bodyweight",
        "difficulty": "Beginner",
        "description": "Isometric core stabilizer for full abdominal endurance.",
        "instructions": "Rest on forearms and toes. Keep body in straight line from head to heels without sagging hips.",
    },
    {
        "name": "Side Plank",
        "category": "Core",
        "muscleGroup": "Obliques",
        "equipment": "Bodyweight",
        "difficulty": "Beginner",
        "description": "Isometric exercise strengthening lateral core and obliques.",
        "instructions": "Lie on side supported by forearm. Stack feet and lift hips off ground into straight line.",
    },
    {
        "name": "Ab Wheel Rollout",
        "category": "Core",
        "muscleGroup": "Rectus Abdominis",
        "equipment": "Bodyweight",
        "difficulty": "Advanced",
        "description": "High-intensity dynamic anti-extension core exercise.",
        "instructions": "Kneel holding ab wheel. Roll wheel forward extending body long, pull back using abdominals.",
    },
    {
        "name": "Hanging Leg Raise",
        "category": "Core",
        "muscleGroup": "Lower Abs & Hip Flexors",
        "equipment": "Bodyweight",
        "difficulty": "Intermediate",
        "description": "Strict lower ab builder performed hanging from a pull-up bar.",
        "instructions": "Hang from bar. Without swinging, lift legs straight up until horizontal with floor.",
    },
    {
        "name": "Cable Crunch",
        "category": "Core",
        "muscleGroup": "Rectus Abdominis",
        "equipment": "Cable",
        "difficulty": "Intermediate",
        "description": "Weighted ab crunch providing progressive overload for abs.",
        "instructions": "Kneel in front of cable stack with rope held behind neck. Flex waist pulling elbows toward knees.",
    },
    {
        "name": "Russian Twist",
        "category": "Core",
        "muscleGroup": "Obliques",
        "equipment": "Bodyweight",
        "difficulty": "Beginner",
        "description": "Rotational ab exercise for oblique development.",
        "instructions": "Sit with knees bent, feet elevated off ground. Rotate torso left and right touching hands to floor.",
    },
    {
        "name": "Bicycle Crunch",
        "category": "Core",
        "muscleGroup": "Rectus Abdominis & Obliques",
        "equipment": "Bodyweight",
        "difficulty": "Beginner",
        "description": "Dynamic alternating crunch motion.",
        "instructions": "Lie on back. Alternate touching right elbow to left knee and left elbow to right knee in cycling motion.",
    },
    {
        "name": "Deadbug",
        "category": "Core",
        "muscleGroup": "Deep Core Stabilizers",
        "equipment": "Bodyweight",
        "difficulty": "Beginner",
        "description": "Safe lumbar-protective core stability drill.",
        "instructions": "Lie on back with arms up and knees bent 90 degrees. Lower opposite arm and leg toward floor slowly.",
    },
    {
        "name": "Resistance Band Woodchopper",
        "category": "Core",
        "muscleGroup": "Obliques & Core",
        "equipment": "Resistance Band",
        "difficulty": "Beginner",
        "description": "Diagonal elastic rotational movement.",
        "instructions": "Anchor band at shoulder height, pull band diagonally across body while rotating torso.",
    },

    # CARDIO
    {
        "name": "Treadmill Running",
        "category": "Cardio",
        "muscleGroup": "Cardiovascular System & Legs",
        "equipment": "Machine",
        "difficulty": "Beginner",
        "description": "Indoor steady-state or interval running exercise.",
        "instructions": "Select speed and incline, maintain upright running posture with natural arm swing.",
    },
    {
        "name": "Outdoor Running",
        "category": "Cardio",
        "muscleGroup": "Cardiovascular System & Legs",
        "equipment": "Bodyweight",
        "difficulty": "Beginner",
        "description": "Classic road or trail running for stamina and health.",
        "instructions": "Pace yourself consistently, land softly on midfoot, breathe rhythmically.",
    },
    {
        "name": "Stationary Cycling",
        "category": "Cardio",
        "muscleGroup": "Cardiovascular System & Quads",
        "equipment": "Machine",
        "difficulty": "Beginner",
        "description": "Low-impact indoor aerobic exercise.",
        "instructions": "Adjust seat height, pedal steadily maintaining cadence between 80-100 RPM.",
    },
    {
        "name": "Rowing Machine (Ergometer)",
        "category": "Cardio",
        "muscleGroup": "Full Body & Cardio",
        "equipment": "Machine",
        "difficulty": "Intermediate",
        "description": "Full-body aerobic conditioning engaging legs, back, and core.",
        "instructions": "Drive with legs, lean back slightly, pull handle to ribs. Reverse order on recovery.",
    },
    {
        "name": "Jump Rope",
        "category": "Cardio",
        "muscleGroup": "Calves & Cardiovascular System",
        "equipment": "Bodyweight",
        "difficulty": "Intermediate",
        "description": "High-density agility and cardiovascular conditioning.",
        "instructions": "Turn rope with wrists, jump softly on balls of feet clearing rope cleanly.",
    },
    {
        "name": "Stair Climber",
        "category": "Cardio",
        "muscleGroup": "Glutes, Calves & Cardio",
        "equipment": "Machine",
        "difficulty": "Intermediate",
        "description": "Continuous stair climbing for lower body endurance.",
        "instructions": "Maintain upright posture on steps without leaning heavily on handrails.",
    },
    {
        "name": "Elliptical Trainer",
        "category": "Cardio",
        "muscleGroup": "Cardiovascular System",
        "equipment": "Machine",
        "difficulty": "Beginner",
        "description": "Smooth low-impact full body aerobic exercise.",
        "instructions": "Step onto pedals, push and pull handles smoothly in rhythmic stride.",
    },
    {
        "name": "Burpees",
        "category": "Cardio",
        "muscleGroup": "Full Body Conditioning",
        "equipment": "Bodyweight",
        "difficulty": "Intermediate",
        "description": "Explosive full-body bodyweight conditioning exercise.",
        "instructions": "Drop into squat, kick feet back to plank, perform push-up, jump feet forward, explode into jump.",
    },
    {
        "name": "Mountain Climbers",
        "category": "Cardio",
        "muscleGroup": "Core & Cardio",
        "equipment": "Bodyweight",
        "difficulty": "Beginner",
        "description": "Fast-paced plank-based cardio burner.",
        "instructions": "Hold plank position, drive knees rapidly toward chest in alternating running motion.",
    },

    # MOBILITY
    {
        "name": "World's Greatest Stretch",
        "category": "Mobility",
        "muscleGroup": "Hips, Hamstrings & Thoracic Spine",
        "equipment": "Bodyweight",
        "difficulty": "Beginner",
        "description": "Comprehensive full-body mobility flow.",
        "instructions": "Step into deep lunge. Place inside hand on floor, rotate opposite elbow upward toward ceiling.",
    },
    {
        "name": "Cat-Cow Stretch",
        "category": "Mobility",
        "muscleGroup": "Spine & Core",
        "equipment": "Bodyweight",
        "difficulty": "Beginner",
        "description": "Gentle spinal flexion and extension mobility movement.",
        "instructions": "On hands and knees. Inhale arching back down (Cow), exhale rounding spine up toward ceiling (Cat).",
    },
    {
        "name": "Hip Opener Frog Stretch",
        "category": "Mobility",
        "muscleGroup": "Adductors & Hips",
        "equipment": "Bodyweight",
        "difficulty": "Beginner",
        "description": "Deep groin and hip adductor stretch.",
        "instructions": "Kneel wide on mat, turn feet outward, gently rock hips back toward heels.",
    },
    {
        "name": "Thoracic Spine Rotation",
        "category": "Mobility",
        "muscleGroup": "Thoracic Spine",
        "equipment": "Bodyweight",
        "difficulty": "Beginner",
        "description": "Improves mid-back rotation for overhead lifting and posture.",
        "instructions": "Quadruped position, place hand behind head. Touch elbow to opposite wrist then rotate open upward.",
    },
    {
        "name": "Shoulder Dislocations (PVC / Band)",
        "category": "Mobility",
        "muscleGroup": "Shoulders & Chest",
        "equipment": "Resistance Band",
        "difficulty": "Beginner",
        "description": "Dynamic shoulder overhead rotation mobility.",
        "instructions": "Hold wide band in front of hips. Raise band straight up over head and behind back smoothly.",
    },
    {
        "name": "Ankle Dorsiflexion Drill",
        "category": "Mobility",
        "muscleGroup": "Ankles & Calves",
        "equipment": "Bodyweight",
        "difficulty": "Beginner",
        "description": "Essential ankle mobility for deep squat depth.",
        "instructions": "Kneel facing wall with front foot 3 inches away. Push knee forward past toes toward wall keeping heel down.",
    },
]


async def seed_exercises() -> None:
    print("Connecting to database...")
    await db.connect()

    print(f"Starting seed process for {len(EXERCISES_DATA)} exercises...")
    created_count = 0
    updated_count = 0

    for item in EXERCISES_DATA:
        existing = await db.exercise.find_unique(where={"name": item["name"]})
        if existing:
            await db.exercise.update(
                where={"name": item["name"]},
                data={
                    "category": item["category"],
                    "muscleGroup": item["muscleGroup"],
                    "equipment": item["equipment"],
                    "difficulty": item["difficulty"],
                    "description": item.get("description"),
                    "instructions": item.get("instructions"),
                },
            )
            updated_count += 1
        else:
            await db.exercise.create(
                data={
                    "name": item["name"],
                    "category": item["category"],
                    "muscleGroup": item["muscleGroup"],
                    "equipment": item["equipment"],
                    "difficulty": item["difficulty"],
                    "description": item.get("description"),
                    "instructions": item.get("instructions"),
                }
            )
            created_count += 1

    print(f"Seeding completed successfully! Created: {created_count}, Updated: {updated_count}, Total: {len(EXERCISES_DATA)}")
    await db.disconnect()


if __name__ == "__main__":
    asyncio.run(seed_exercises())
